spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auction_system
    username: root
    password: 0344227892@Triet
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
